package com.soildtunnel.desktop.core

/** Maps /24 prefixes to two-letter country codes. */
object GeoTable {

    /** Country of one Cloudflare datacenter. */
    data class Colo(
        val iso: String,
        val country: String,
    )

    private val TABLE: Map<String, Colo> = mapOf(

        // Europe
        "AMS" to Colo("NL", "Netherlands"),
        "EIN" to Colo("NL", "Netherlands"),
        "FRA" to Colo("DE", "Germany"),
        "DUS" to Colo("DE", "Germany"),
        "HAM" to Colo("DE", "Germany"),
        "BER" to Colo("DE", "Germany"),
        "MUC" to Colo("DE", "Germany"),
        "STR" to Colo("DE", "Germany"),
        "NUE" to Colo("DE", "Germany"),
        "LHR" to Colo("GB", "United Kingdom"),
        "MAN" to Colo("GB", "United Kingdom"),
        "EDI" to Colo("GB", "United Kingdom"),
        "CDG" to Colo("FR", "France"),
        "MRS" to Colo("FR", "France"),
        "LYS" to Colo("FR", "France"),
        "NCE" to Colo("FR", "France"),
        "BRU" to Colo("BE", "Belgium"),
        "DUB" to Colo("IE", "Ireland"),
        "MAD" to Colo("ES", "Spain"),
        "BCN" to Colo("ES", "Spain"),
        "AGP" to Colo("ES", "Spain"),
        "LIS" to Colo("PT", "Portugal"),
        "OPO" to Colo("PT", "Portugal"),
        "MXP" to Colo("IT", "Italy"),
        "FCO" to Colo("IT", "Italy"),
        "PMO" to Colo("IT", "Italy"),
        "VIE" to Colo("AT", "Austria"),
        "ZRH" to Colo("CH", "Switzerland"),
        "GVA" to Colo("CH", "Switzerland"),
        "BSL" to Colo("CH", "Switzerland"),
        "CPH" to Colo("DK", "Denmark"),
        "ARN" to Colo("SE", "Sweden"),
        "GOT" to Colo("SE", "Sweden"),
        "OSL" to Colo("NO", "Norway"),
        "HEL" to Colo("FI", "Finland"),
        "TLL" to Colo("EE", "Estonia"),
        "RIX" to Colo("LV", "Latvia"),
        "VNO" to Colo("LT", "Lithuania"),
        "WAW" to Colo("PL", "Poland"),
        "KRK" to Colo("PL", "Poland"),
        "POZ" to Colo("PL", "Poland"),
        "PRG" to Colo("CZ", "Czechia"),
        "BUD" to Colo("HU", "Hungary"),
        "OTP" to Colo("RO", "Romania"),
        "CLJ" to Colo("RO", "Romania"),
        "SOF" to Colo("BG", "Bulgaria"),
        "BEG" to Colo("RS", "Serbia"),
        "ZAG" to Colo("HR", "Croatia"),
        "LJU" to Colo("SI", "Slovenia"),
        "SKG" to Colo("GR", "Greece"),
        "ATH" to Colo("GR", "Greece"),
        "KEF" to Colo("IS", "Iceland"),
        "LUX" to Colo("LU", "Luxembourg"),

        // Middle East
        "IST" to Colo("TR", "Turkey"),
        "SAW" to Colo("TR", "Turkey"),
        "ESB" to Colo("TR", "Turkey"),
        "AYT" to Colo("TR", "Turkey"),
        "DXB" to Colo("AE", "United Arab Emirates"),
        "AUH" to Colo("AE", "United Arab Emirates"),
        "DOH" to Colo("QA", "Qatar"),
        "KWI" to Colo("KW", "Kuwait"),
        "BAH" to Colo("BH", "Bahrain"),
        "MCT" to Colo("OM", "Oman"),
        "RUH" to Colo("SA", "Saudi Arabia"),
        "JED" to Colo("SA", "Saudi Arabia"),
        "TLV" to Colo("IL", "Israel"),
        "AMM" to Colo("JO", "Jordan"),
        "BEY" to Colo("LB", "Lebanon"),
        "BGW" to Colo("IQ", "Iraq"),
        "BSR" to Colo("IQ", "Iraq"),
        "EBL" to Colo("IQ", "Iraq"),
        "GYD" to Colo("AZ", "Azerbaijan"),
        "TBS" to Colo("GE", "Georgia"),
        "EVN" to Colo("AM", "Armenia"),
        "ALA" to Colo("KZ", "Kazakhstan"),
        "NQZ" to Colo("KZ", "Kazakhstan"),
        "TAS" to Colo("UZ", "Uzbekistan"),
        "FRU" to Colo("KG", "Kyrgyzstan"),

        // South Asia
        "BOM" to Colo("IN", "India"),
        "DEL" to Colo("IN", "India"),
        "AMD" to Colo("IN", "India"),
        "MAA" to Colo("IN", "India"),
        "BLR" to Colo("IN", "India"),
        "CCU" to Colo("IN", "India"),
        "HYD" to Colo("IN", "India"),
        "CMB" to Colo("LK", "Sri Lanka"),
        "KHI" to Colo("PK", "Pakistan"),
        "LHE" to Colo("PK", "Pakistan"),
        "ISB" to Colo("PK", "Pakistan"),
        "DAC" to Colo("BD", "Bangladesh"),
        "KTM" to Colo("NP", "Nepal"),

        // East Asia
        "SIN" to Colo("SG", "Singapore"),
        "KUL" to Colo("MY", "Malaysia"),
        "BKK" to Colo("TH", "Thailand"),
        "CNX" to Colo("TH", "Thailand"),
        "HAN" to Colo("VN", "Vietnam"),
        "SGN" to Colo("VN", "Vietnam"),
        "CGK" to Colo("ID", "Indonesia"),
        "DPS" to Colo("ID", "Indonesia"),
        "MNL" to Colo("PH", "Philippines"),
        "HKG" to Colo("HK", "Hong Kong"),
        "TPE" to Colo("TW", "Taiwan"),
        "ICN" to Colo("KR", "South Korea"),
        "PUS" to Colo("KR", "South Korea"),
        "NRT" to Colo("JP", "Japan"),
        "KIX" to Colo("JP", "Japan"),
        "FUK" to Colo("JP", "Japan"),
        "CTS" to Colo("JP", "Japan"),

        // Americas
        "JFK" to Colo("US", "United States"),
        "EWR" to Colo("US", "United States"),
        "IAD" to Colo("US", "United States"),
        "ORD" to Colo("US", "United States"),
        "DFW" to Colo("US", "United States"),
        "IAH" to Colo("US", "United States"),
        "ATL" to Colo("US", "United States"),
        "MIA" to Colo("US", "United States"),
        "MCO" to Colo("US", "United States"),
        "CLT" to Colo("US", "United States"),
        "PHL" to Colo("US", "United States"),
        "BOS" to Colo("US", "United States"),
        "DTW" to Colo("US", "United States"),
        "MSP" to Colo("US", "United States"),
        "DEN" to Colo("US", "United States"),
        "PHX" to Colo("US", "United States"),
        "SEA" to Colo("US", "United States"),
        "SFO" to Colo("US", "United States"),
        "SJC" to Colo("US", "United States"),
        "LAX" to Colo("US", "United States"),
        "SLC" to Colo("US", "United States"),
        "YYZ" to Colo("CA", "Canada"),
        "YVR" to Colo("CA", "Canada"),
        "YUL" to Colo("CA", "Canada"),
        "YOW" to Colo("CA", "Canada"),
        "YEG" to Colo("CA", "Canada"),
        "YYZ2" to Colo("CA", "Canada"),
        "MEX" to Colo("MX", "Mexico"),
        "GDL" to Colo("MX", "Mexico"),
        "TIJ" to Colo("MX", "Mexico"),
        "QRO" to Colo("MX", "Mexico"),
        "PTY" to Colo("PA", "Panama"),
        "SJO" to Colo("CR", "Costa Rica"),
        "BOG" to Colo("CO", "Colombia"),
        "LIM" to Colo("PE", "Peru"),
        "GRU" to Colo("BR", "Brazil"),
        "GIG" to Colo("BR", "Brazil"),
        "BSB" to Colo("BR", "Brazil"),
        "CWB" to Colo("BR", "Brazil"),
        "POA" to Colo("BR", "Brazil"),
        "FOR" to Colo("BR", "Brazil"),
        "REC" to Colo("BR", "Brazil"),
        "SSA" to Colo("BR", "Brazil"),
        "EZE" to Colo("AR", "Argentina"),
        "SCL" to Colo("CL", "Chile"),
        "MVD" to Colo("UY", "Uruguay"),

        // Africa/Oceania
        "CMN" to Colo("MA", "Morocco"),
        "RAK" to Colo("MA", "Morocco"),
        "ALG" to Colo("DZ", "Algeria"),
        "TUN" to Colo("TN", "Tunisia"),
        "CAI" to Colo("EG", "Egypt"),
        "ACC" to Colo("GH", "Ghana"),
        "ABJ" to Colo("CI", "Ivory Coast"),
        "LOS" to Colo("NG", "Nigeria"),
        "NBO" to Colo("KE", "Kenya"),
        "DAR" to Colo("TZ", "Tanzania"),
        "MRU" to Colo("MU", "Mauritius"),
        "JNB" to Colo("ZA", "South Africa"),
        "CPT" to Colo("ZA", "South Africa"),
        "DUR" to Colo("ZA", "South Africa"),
        "SYD" to Colo("AU", "Australia"),
        "MEL" to Colo("AU", "Australia"),
        "BNE" to Colo("AU", "Australia"),
        "PER" to Colo("AU", "Australia"),
        "ADL" to Colo("AU", "Australia"),
        "AKL" to Colo("NZ", "New Zealand"),
    )

    /** Lookup by colo code; null when the code is not in the table. */
    fun byColo(colo: String?): Colo? = colo?.let { TABLE[it.uppercase()] }
}
